name: Flyway GitHub Actions SQL Server Workflow # Workflow name
on:
  push:
    paths:
    - 'migrations/**'

# Environment Variables
env:
  # Repository Variables - Create these in Project Settings > Variables > Actions
  EMAIL: ${{ vars.USER_EMAIL }} # Use with ${{ env.EMAIL }}
  DB_SERVER: ${{ vars.DB_SERVER }}
  DB_QA: ${{ vars.DB_NAME_QA }}
  ENCRYPT: ${{ vars.ENCRYPT_BOOL }}
  TRUST_CERT: ${{ vars.TRUST_CERT_BOOL }}
  # BASELINE_VERSION: ${{ vars.BASELINE_VERSION }}
  
  # Repository Secrets - Create these in Project Settings > Secrets > Actions
  TOKEN: ${{ secrets.FLYWAY_TOKEN }} 
  DB_USER_QA: ${{ secrets.DB_USER_NAME_QA }}
  DB_USER_PW_QA: ${{ secrets.DB_USER_PW_QA }}
  # FIRST_UNDO_SCRIPT: ${{ secrets.FIRST_UNDO_SCRIPT }} # Validates all undo scripts up to and including the specified script

# jobs are the steps executed in the workflow
jobs:
  flyway-migrate: # Job name
    runs-on: self-hosted # Runner to execute the job
    # runs-on: ubuntu-latest
    defaults:
      run:
        shell: cmd # Default shell. Use Windows Command Prompt

    steps: # Steps are the individual tasks that are executed in the job
      - uses: actions/checkout@v4 # Check out the repository
        with: # Additional options for the action
          ref: "main" # Branch to check out

      - name: Flyway Migrate # Step to run Flyway migrations
        # To use username and password instead of windows integrated security Ensure that SQL Server is configured to allow SQL Server authentication. You can check this in SQL Server Management Studio (SSMS) under the server properties -> Security -> Server authentication. Ensure "SQL Server and Windows Authentication mode" is selected.
        run: flyway -email=${{ env.EMAIL }} -token=${{ env.TOKEN }} migrate -user=${{ env.DB_USER_QA }} -password=${{ env.DB_USER_PW_QA }} -url="${{ env.DB_SERVER }};databaseName=${{ env.DB_QA }};encrypt=${{ env.ENCRYPT }};trustServerCertificate=${{ env.TRUST_CERT }}" -IAgreeToTheEula -locations="filesystem:${{ github.workspace }}/migrations" -configFiles="${{ github.workspace }}/flyway.toml" -baselineOnMigrate=true -errorOverrides=S0001:0:I-
        working-directory: ./migrations
        # Sample for integrated security instead of user name and password
        # -url="${{ env.DB_SERVER }};databaseName=${{ env.DB_QA }};encrypt=${{ env.ENCRYPT }};integratedSecurity=true;trustServerCertificate=${{ env.TRUST_CERT }}"
        # -baselineVersion=${{ env.BASELINE_VERSION }}
        # -user=${{ env.DB_USER_QA }} -password=${{ env.DB_USER_PW_QA }}